amitsi/pluribus-ansible

ansible/library/pn_vxlan.py, ansible/library/pn_ztp_vrrp_l3.py
- Removed VXLAN code from VRRP module
- Added new Ansible module for VXLAN
- Updated VXLAN code in the module
=> Added VXLAN module

ansible/library/pn_vxlan.py, ansible/library/pn_ztp.py, ansible/library/pn_ztp_vrrp_l3.py, ansible/playbooks/pn_vxlan.yml
- Updated vxlan module
- Cleaned up VRRP L3 module
- Updated ZTP module
- Added playbook for vxlan
=> VXLAN module updates

ansible/library/pn_initial_ztp.py, ansible/library/pn_l2_ztp.py, ansible/playbooks/pn_initial_ztp.yml, ansible/playbooks/pn_l2_ztp.yml, ansible/playbooks/pn_switch_reset.yml
- Segregated `pn_ztp.py` module into `pn_initial_ztp.py` (initial setup) and `pn_l2_ztp.py` (auto vlags).
- Created playbooks for these two new modules.
- Updated `pn_switch_reset.yml` playbook.
=> Segregation of ZTP ansible module

ansible/library/pn_ebgp_ospf.py, ansible/playbooks/pn_vrrp_l3_bfd.yml
1.The file pn_ebgp.py is changed to pn_ebgp_ospf.py
2.The necessary changes made in pn_vrrp_l3_bfd.yml
3.The flag pn_routing_protocol should be used to configure the routing protocol needed.
4.The choices for pn_routing_protocol are ['ebgp', 'ospf']
=> Configured routing protocol OSPF 

ansible/library/pn_initial_ztp.py
=> Added missing addition assignemnt operator

ansible/library/pn_ebgp_ospf.py, ansible/library/pn_initial_ztp.py, ansible/library/pn_l2_ztp.py, ansible/library/pn_l3_ztp.py, ansible/library/pn_ztp_vrrp_l2_csv.py, ansible/library/pn_ztp_vrrp_l3.py
Following modules have been cleaned up and updated:
- Initial ZTP (Fabric creation)
- L2 ZTP (Auto vlags)
- L3 ZTP (Link ips)
- L2 VRRP
- L3 VRRP
- EBGP & OSPF
=> Updated Ansible Modules

ansible/playbooks/advance/gui_l2_vrrp.yml, ansible/playbooks/advance/gui_l3_vrrp.yml, ansible/playbooks/advance/vars_l2_vrrp.yml, ansible/playbooks/advance/vars_l3_vrrp.yml
L2 VRRP and L3 VRRP playbooks now have only one variable file apart from `cli_vault.yml`.
=> Updated GUI playbooks to have one variable file

ansible/library/pn_initial_ztp.py
=> Fix for in-band ip assignment

ansible/library/tests/pn_test_l2_vrrp.py, ansible/library/tests/pn_test_l3_vrrp.py, ansible/library/tests/pn_test_ztp_l2.py, ansible/playbooks/pn_test_l2_vrrp.yml, ansible/playbooks/pn_test_l3_vrrp.yml, ansible/playbooks/pn_test_ztp_l2.yml
- Added Ansible modules for L2 & L3 VRRP tests
- Added automation tests playbooks for L2 & L3 VRRP
- Updated existing test modules and playbooks of L2 & L3 ZTP
=> Automation tests for L2 & L3 VRRP

ansible/playbooks/advance/playbooks/pn_test_l2_vrrp.yml, ansible/playbooks/advance/playbooks/pn_test_l3_vrrp.yml
- L2 VRRP tests
- L3 VRRP tests
=> Added test automation playbooks to advance folder for GUI

ansible/library/pn_l2_ztp.py
Removed extra indentation to fix [#94](https://github.com/amitsi/pluribus-ansible/issues/94)
=> Removed extra Indentation

ansible/library/pn_l3_ztp.py
=> Fix for trunk delete

ansible/library/pn_initial_ztp_withthread.py, ansible/library/pn_l2_ztp_json.py, ansible/library/pn_ztp_vrrp_l2_csv_json.py
*Initial ztp with multithreading doesn't display all the cli outputs in the shell.
It creates a file called output.txt on every switch in the username's(used) home folder. 
The file output.txt contain a hint of every task run.*
=> Added json to l2 modules + initial ztp with multithreading

ansible/dci.csv, ansible/library/pn_dci.py, ansible/playbooks/pn_dci.yml, ansible/third_party_dci.csv
This pull request contains:
- Updates to Ansible DCI module `pn_dci.py`
- Addition of `pn_dci.yml` playbook
- Addition of CSV files required for DCI implementation
=> DCI module updates

ansible/library/tests/pn_test_ebgp_ospf.py, ansible/library/tests/pn_test_l3_vrrp_third_party.py, ansible/library/tests/pn_test_ztp_l3_third_party.py, ansible/playbooks/tests/pn_test_l3_vrrp.yml, ansible/playbooks/tests/pn_test_ztp_l3.yml
Added test modules for:
- L3 ZTP with 3rd party switches
- L3 VRRP with 3rd party switches
Also added `OSPF` tests in existing `eBGP` test module and updated tests playbooks
=> Automation test modules for L3 with third party switches

ansible/library/pn_initial_ztp.py, ansible/library/pn_initial_ztp_json.py
=> [Master] Updated enable_ports() method to fix changed=True/1 issue on rerun

ansible/library/pn_initial_ztp.py
=> [Release 2.2.0] Updated enable_ports() method to fix changed=True/1 issue on rerun

ansible/playbooks/pn_validate_json.py
To check if a playbook output is a valid/invalid json object and to check if that json object contains all the required fields (like status, summary, msg, etc) then run this script as:
`python pn_validation_json.py playbook.yml`
Example: To validate output of `pn_initial_ztp.yml` playbook, run this command:
`python pn_validation_json.py pn_initial_ztp.yml`
=> Modified json validation script

ansible/library/pn_initial_ztp.py
=> Convert `msg` field in module.exit_json() to string

ansible/library/pn_initial_ztp.py, ansible/library/pn_l2_ztp.py, ansible/library/pn_ztp_vrrp_l2_csv.py
- Updated documentation
- Updated output messages
- Made code compliant with PEP8
- For failure, updated `output` field to contain failed cli command as a string instead of list
- For failure, updated `exception` fields so that it will now contain error message (stderr value)
- Removed unnecessary `stderr` field from failure payload
- Updated `task` and `msg` field in payload for both success and failure case
- Modules updated: `pn_initial_ztp.py`, `pn_l2_ztp.py` and `pn_vrrp_l2_csv.py`
=> [Release-2.2.0] Updates to Ansible modules

ansible/library/pn_ebgp_ospf_additional_switches.py, ansible/library/pn_initial_ztp_additional_switches.py, ansible/library/pn_l3_ztp_additional_switches.py, ansible/playbooks/pn_l3_vrrp_ebgp_additional_switch.yml, ansible/playbooks/pn_l3_vrrp_ospf_additional_switches.yml
The groups considered in the hosts file are:
spine
leaf
new_spine
new_leaf
=> working code of initial ztp + l3 ztp + l3 vrrp + ebgp with additional switches(documentation left)

ansible/library/pn_l2_ztp_additional_switches.py, ansible/playbooks/pn_l2_ztp_additional_switches.yml
Module: `pn_l2_ztp_additional_switches.py`
Playbook: `pn_l2_ztp_additional_switches.yml`
=> Additional switches module for L2 ZTP

ansible/pn_l2_csv_validation.py
Example:
`python pn_l2_csv_validation.py pn_vrrp_l2.csv`
If needed, it can be easily converted to Ansible module. But before we do that, we need to decide upon the module output, task output and also handling that output from front-end side.
=> L2 VRRP CSV validation script

ansible/library/pn_l2_vrrp_csv_validation.py, ansible/playbooks/gui_l2_vrrp.yml, ansible/playbooks/gui_l2_vrrp_csv_validation.yml
Output:
```
root@amitsi:/etc/ansible/pluribus-ansible/ansible/playbooks# ansible-playbook -i hosts l2_csv_validation.yml 
__________ANSIBLE_TASK_BOUNDARY_STARTS__________
{
"plays": [
{
"play": {
"id": "201a6e18-a5b1-4f7c-9f50-d0dc3f27f1d5", 
"name": "Validate L2 VRRP CSV File"
}, 
"tasks": [
{
"hosts": {
"localhost": {
"_ansible_no_log": false, 
"_ansible_parsed": true, 
"changed": false, 
"exception": "", 
"failed": true, 
"invocation": {
"module_args": {
"pn_csv_data": "1a1.108.100.0/24, 100, test-spine1\n101.108.101.0/24, 10199, test-spine1\n101.108.102.0/24, 102, test-spine2\n101.108.103.0/24, 103, test-spine2\n198.168.1.1/32, 102, test-spine2\n , , , , , \n, ,"
}, 
"module_name": "pn_l2_vrrp_csv_validation"
}, 
"msg": "Invalid csv file", 
"summary": "Invalid IP 1a1.108.100.0/24 at …
```
=> Created separate playbook for l2 vrrp csv validation

ansible/playbooks/gui_fabric_creation.yml, ansible/playbooksConfiguration.xml
- Set pn_static_setup to true
-  Removed pn_web_api
-  Removed pn_static_setup and pn_web_api
=> Chnages and playbook and Xml file.

ansible/library/pn_initial_ztp.py
=> Fixed issue in update_switch_names() method

ansible/library/pn_hosts_file_validation.py, ansible/library/pn_l2_vrrp_csv_validation.py
Updated both csv and hosts file validation modules
=> Updated validation modules

ansible/pn_enable_root_ssh.yml, ansible/pn_vrouter_ping_test.py
For the root_ssh_enable playbook, please go through the doc in the playbook itself.
Completed the vrouter-ping script with the requirement not to ping the slave ips.
The character limit per line the script is considered to be 160.
To run: use the command `python pn_vrouter_ping_test.py`
=> Documented the root_enable playbook and included the mechanism to take the root-password from vault file.

ansible/pn_paramiko.py
Add this plugin to `/usr/lib/python2.7/dist-packages/ansible/plugins/connection`
and update `transport = pn_paramiko` in `ansible.cfg`
=> PN Paramiko Connection Plugin

docs/module_docs/txt_module_docs/pn_initial_ztp.txt, docs/module_docs/txt_module_docs/pn_l2_ztp.txt
Created txt docs for modules:
- `pn_initial_ztp` (Fabric creation)
- `pn_l2_ztp` (vLag creation)
=> [master] 1 pager module docs

ansible/library/pn_l3_ztp.py, ansible/playbooks/gui_l3_ztp.yml
Added module: `pn_l3_ztp.py` and playbook: `gui_l3_ztp.yml` for L3 ZTP
=> [release-2.3.0] Added module and playbook for L3 ZTP

ansible/library/pn_l3_ztp.py, ansible/playbooks/gui_l3_ztp.yml
Added `pn_l3_ztp.py` module and `gui_l3_ztp.yml` playbook
=> [release-2.2.0] Added L3 ZTP module and playbook

ansible/playbooksConfiguration.xml
add L3 vrrp with ebgp and ospf playbooks
=> add L3 vrrp with ebgp and ospf playbooks

ansible/library/pn_ebgp_ospf_third_party.py, ansible/library/pn_l2_third_party.py, ansible/library/pn_l3_vrrp.py, ansible/library/pn_l3_vrrp_third_party.py, ansible/library/pn_l3_ztp_third_party.py, ansible/playbooks/gui_l2_third_party.yml, ansible/playbooks/gui_l3_vrrp_ebgp_third_party.yml, ansible/playbooks/gui_l3_vrrp_ospf_third_party.yml, ansible/playbooks/gui_l3_ztp_third_party.yml
Modules: 
- `pn_l2_third_part.py`
- `pn_l3_ztp_third_party.py`
- `pn_l3_vrrp_third_party.py`
- `pn_ebgp_ospf_third_party.py`
Playbooks: 
- `gui_l2_third_party.yml`
- `gui_l3_ztp_third_party.yml`
- `gui_l3_vrrp_ebgp_third_party.yml`
- `gui_l3_vrrp_ospf_third_party.yml`
=> [release-2.3.0] Added modules & playbooks for L2/L3 with 3rd party switches

ansible/playbooksConfiguration.xml
playbook xml file with l3 ebgp and ospf
=> playbook xml file with l3 ebgp and ospf

ansible/library/pn_ebgp_ospf.py, ansible/library/pn_ebgp_ospf_third_party.py
Assign router id only if loopback ips have been assigned
=> [release 2.3.0] Updates to ebgp/ospf modules

ansible/library/pn_ebgp_ospf.py
Assign router id only if loopback ips have been assigned
=> [release-2.2.0] Updated assign_router_id function in ebgp/ospf module

ansible/library/pn_ebgp_ospf_json.py, ansible/library/pn_ebgp_ospf_thirdparty_json.py, ansible/pn_paramiko.py
Add this plugin to `/usr/lib/python2.7/dist-packages/ansible/plugins/connection`
and update `transport = pn_paramiko` and `remote_tmp = /tmp` in ansible.cfg
=> Made changes to pn_paramiko plugin

ansible/common/pn_ansible_lib.py, test/pn_ansible_lib_tests.py, util/README.md, util/build_release.py, util/run.sh
This push is in regards to #196, however I am not confident that we can call the issue "closed". Would like feedback on status of #196
This also addresses #197, however the issue will still exist until we decide on a permanent solution. I am currently testing with pre-pended library files, however with some tweaking the environment can be made to accept pushing of fully built library files to the destination switches for testing. This does not give a permanent solution however.
ansible/common/pn_ansible_lib.py:
- Bring code quality up to pylint and pep8 standards.
- Modified the calc_link_ip_addr to remove redundant declerations and conform to pylint standards.
- Added headers to break code into sections.
- Changed send_command to look for errors rather than the complicated logic to …
=> push library for review

ansible/common/pn_ansible_lib.py
pn_ansible_lib.py:
- added docstring to calc_link_up_addr
- changed line 96 to be better style
- removed auto_accept_eula method
- passing pep8
=> fixes for #231 review

ansible/playbooksConfiguration.xml
removed pn_assign_loopback field
=> removed pn_assign_loopback field

ansible/playbooksConfiguration.xml
added suport for downloading sample CSV and Host file
=> added suport for downloading sample CSV and Host file

ansible/playbooksConfiguration.xml
=> added images for playbook

ansible/playbooksConfiguration.xml
=> added images to playbook

ansible/playbooksConfiguration.xml
Bug #16759 : Correcting yml file for gui_l2_vrrp_thirdparty
=> Bug #16759 : Correcting yml file for gui_l2_vrrp_thirdparty

ansible/playbooksConfiguration.xml
- added description to playbooks
=> added description to playbooks

ansible/playbooksConfiguration.xml
- added description to playbooks
- added support for downloading sample host and csv file
=> added description to playbooks and added support for downloading sample host and csv file

ansible/playbooks/gui_switch_reset.yml
resetting the particular set of switches based on user input
=> resetting the particular set of switches based on user input

ansible/playbooks/gui_fabric_creation.yml, ansible/playbooks/gui_hosts_validation.yml, ansible/playbooks/gui_l2_third_party.yml, ansible/playbooks/gui_l2_vrrp.yml, ansible/playbooks/gui_l2_vrrp_csv_validation.yml, ansible/playbooks/gui_l3_vrrp_csv_validation.yml, ansible/playbooks/gui_l3_vrrp_ebgp.yml, ansible/playbooks/gui_l3_vrrp_ebgp_third_party.yml, ansible/playbooks/gui_l3_vrrp_ospf.yml, ansible/playbooks/gui_l3_vrrp_ospf_third_party.yml, ansible/playbooks/gui_l3_ztp.yml, ansible/playbooks/gui_l3_ztp_third_party.yml
removed unused file playbook-variable.yml file from playbooks
=> removed unused file playbook-variable.yml file from playbooks

ansible/playbooks/gui_switch_reset.yml, ansible/playbooksConfiguration.xml
added support for playbook field validation
=> added support for playbook field validation

ansible/library/pn_eula_accept.py, ansible/library/pn_fabric_creation.py, ansible/playbooks/pn_fabric_creation.yml, ansible/playbooks/pn_switch_reset.yml, ansible/pn_paramiko.py
- Updated `pn_paramiko.py` connection plugin
- Created new module for eula accept `pn_eula_accept.py`
- Created new module for fabric creation `pn_fabric_creation.py`
- Updated switch reset module `pn_switch_config_reset.py`
- Updated switch reset playbook `pn_switch_reset.yml`
- Created new playbook for eula accept and fabric creation `pn_fabric_creation.yml`
=> [aaa-tacacs] New module/playbooks for eula, fabric create, switch reset

ansible/playbooksConfiguration.xml
added dlink l2 playbook
corrected regex
=> added dlink l2 playbook

ansible/library/dlink_fabric_creation.py, ansible/library/dlink_l2.py, ansible/playbooks/gui_dlink_fabric_creation.yml, ansible/playbooks/gui_dlink_l2.yml
Playbooks:
- Fabric creation: `dlink_fabric_creation.yml`
- L2 vrrp: `dlink_l2.yml`
=> [release-2.3.0] Updated dlink modules and playbook

ansible/playbooksConfiguration.xml
added fabric creation playbbok for dlink and removed indand field for dlink l2
=> added fabric creation playbbok for dlink and removed indand field for dlink l2

ansible/playbooks/l2_cluster_vrrp.yml, ansible/playbooks/l2_single_switch.yml, ansible/playbooks/l2_two_switch_cluster.yml, ansible/playbooks/l3_single_routed_bgp.yml, ansible/playbooks/l3_single_routed_ospf.yml, ansible/playbooksConfiguration.xml
=> Dlink changes

ansible/playbooks/l3_bgp_with_vrrp.yml, ansible/playbooks/l3_ospf_with_vrrp.yml, ansible/playbooks/l3_single_routed_bgp_with_l2.yml, ansible/playbooks/l3_single_routed_ospf_with_l2.yml
=> change variable name

ansible/playbooksConfiguration.xml
=> sample host and csv files

ansible/playbooksConfiguration.xml
=> added pn_assign_loopback

ansible/playbooksConfiguration.xml
=> rearrange playbook sequence

ansible/library/pn_switch_config_reset.py
Added check to see if switch is unreachable
=> [release-2.3.0] Updated switch reset module

ansible/playbooksConfiguration.xml
=> updated playbook icons

ansible/playbooksConfiguration.xml
=> corrected toogle 40g text

ansible/playbooksConfiguration.xml
making trunk and vlag optional
=> making trunk and vlag optional

ansible/playbooksConfiguration.xml
=> remove pn_assing_loopback

ansible/library/pn_switch_config_reset.py, ansible/playbooks/gui_switch_reset.yml
Fix for bug: [17399](https://bugs.pluribusnetworks.com/show_bug.cgi?id=17399)
=> [release-2.3.0] Updated switch config reset module and playbook

ansible/playbooksConfiguration.xml
=> change regex for fabric name

ansible/library/dlink_fabric_creation.py
Fix for bug [17494](https://bugs.pluribusnetworks.com/show_bug.cgi?id=17494)
=> [release-2.3.0] Updated dlink fabric creation module to fix bug 17494

ansible/playbooksConfiguration.xml
Bug #17328 - Making Vlag optional ibn l2 2 switch cluster
=> Bug #17328 - Making Vlag optional ibn l2 2 switch cluster

ansible/playbooksConfiguration.xml
Bug #17543 - Correcting loopback ip
=> Bug #17543 - Correcting loopback ip

ansible/playbooksConfiguration.xml
Updated D-link fabric creation xml file to include new values
=> Updated D-link fabric creation xml file to include new values

ansible/library/dlink_fabric_creation.py, ansible/playbooks/gui_dlink_fabric_creation.yml
- Added switch setup code to the module
- Added switch setup params to the playbook
- Added update switch name method in the module
=> [release-2.3.0] Updated dlink fabric creation playbook

ansible/library/pn_eula_accept.py, ansible/playbooks/gui_fabric_creation.yml
=> [release-2.3.0] Revert fix for bug 17658

ansible/library/pn_l3_ztp.py
Avoid input parameter modification to prevent repetition of messages.
=> avoid input modification - pn_spine_list
